name: Sync to Hugging Face Hub

on:
  push:
    branches: [ main ]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # <--- Ini tambahan penting supaya riwayat kodenya utuh

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote add hf https://user:$HF_TOKEN@huggingface.co/spaces/salsabilaslh/CICD_Gradio
          git push --force hf main:main